import {
  Home,
  LayoutDashboard,
  Activity,
  BarChart3,
  FileQuestion,
  Compass,
  Map,
  Star,
  Info,
  CheckCircle,
  Mail,
  HelpCircle,
  MessageSquare,
  Users,
  Settings,
  Target,
  LogIn,
  UserPlus,
  Lock,
  Shield,
  Cookie,
  Briefcase,
  BookOpen,
  Search,
  ActivityIcon,
} from "lucide-react";

export const navigationLinks = [
  { name: "Home", href: "/", icon: Home, category: "Main" },
  { name: "Dashboard", href: "/dashboard", icon: LayoutDashboard, category: "Main" },
  { name: "Search", href: "/search", icon: Search, category: "Main" },
  { name: "Overview", href: "/overview", icon: Activity, category: "Learning" },
  { name: "Analytics", href: "/analytics", icon: BarChart3, category: "Learning" },
  { name: "Assessment", href: "/assessment", icon: FileQuestion, category: "Learning" },
  { name: "Guidance", href: "/guidance", icon: Compass, category: "Learning" },
  { name: "Roadmap", href: "/roadmap", icon: Map, category: "Learning" },
  { name: "Features", href: "/features", icon: Star, category: "Info" },
  { name: "About", href: "/about", icon: Info, category: "Info" },
  { name: "How It Works", href: "/how-it-works", icon: CheckCircle, category: "Info" },
  { name: "Contact", href: "/contact", icon: Mail, category: "Info" },
  { name: "Reviews", href: "/reviews", icon: Star, category: "Info" },
  { name: "Developer", href: "/developer", icon: Users, category: "Info" },
  { name: "Help", href: "/help", icon: HelpCircle, category: "Support" },
  { name: "FAQ", href: "/faq", icon: MessageSquare, category: "Support" },
  { name: "Documentation", href: "/docs", icon: BookOpen, category: "Support" },
  { name: "Status", href: "/status", icon: ActivityIcon, category: "Support" },
  { name: "Profile", href: "/profile", icon: Users, category: "Account" },
  { name: "Settings", href: "/settings", icon: Settings, category: "Account" },
  { name: "Onboarding", href: "/onboarding", icon: Target, category: "Account" },
  { name: "Login", href: "/login", icon: LogIn, category: "Auth" },
  { name: "Sign Up", href: "/signup", icon: UserPlus, category: "Auth" },
  { name: "Forgot Password", href: "/forgot-password", icon: Lock, category: "Auth" },
  { name: "Verify Email", href: "/verify-email", icon: Mail, category: "Auth" },
  { name: "Privacy Policy", href: "/privacy", icon: Shield, category: "Legal" },
  { name: "Terms & Conditions", href: "/terms", icon: FileQuestion, category: "Legal" },
  { name: "Cookie Policy", href: "/cookies", icon: Cookie, category: "Legal" },
  { name: "Security", href: "/security", icon: Lock, category: "Legal" },
  { name: "Admin", href: "/admin", icon: Briefcase, category: "Admin" },
];

export const categories = ["Main", "Learning", "Info", "Support", "Account", "Auth", "Legal", "Admin"];
